### ISSUE TITLE
Continuidade

### ISSUE THREAD

**Issue by geich** [camisnew/products-dashboard#1]
Oi Camis.

Vc poderia enviar o que fez até agora? ainda podemos te incluir no processo mesmo com o projeto não finalizado.

**Comment by camisnew** [comment]
Vou dar um push aqui peraí

Em sex., 13 de nov. de 2020 às 12:13, Gabriel Eich <notifications@github.com>
escreveu:

**Comment by camisnew** [comment]
Opa! Tive um probleminha pra ignorar o node_modules, mas já foi! Posso
continuar trabalhando no projeto? Aí depois do almoço faço um readme e
commito ele com uma identificação pra vocês verem até onde fui até o
presente momento.

Em sex., 13 de nov. de 2020 às 12:16, Camila Berthold Pires <
camilabertholdpires@gmail.com> escreveu:

**Comment by geich** [comment]
Ok, faz o Readme e envia, descreve o que vc n conseguiu implementar junto com os outros requisitos por favor.

**Comment by camisnew** [comment]
Readme tá na mão e junto com ele ajustei algumas coisas pra garantir que dá pra rodar (:

**Comment by geich** [comment]
Nice!
